print("Let's play Mad libs! (Press enter to continue)")
adjective = input("Adjective: ")
food1 = input("Foods (plural): ")
verb = input("Verb: ")
saying = input("Saying (phrase): ") 
noun = input("Noun: ")
food2 = input("Foods (plural): ")
color = input("Color: ")
ride = input("Something you would ride in: ")
animal = input("Animal: ")
person = input("Person: ")
answer = input("Alright, all done! Do you want to hear the madlib? (Type 'Yes', or 'No')")
if answer == "Yes":
    print(f"Today I went to my favorite Taco Stand called the {adjective} {animal}.")
    print(f"Unlike most food stands, they cook and prepare the food in a {ride} while you {verb}.")
    print(f"The best thing on the menu is the {color} {noun}.")
    print(f"Instead of ground beef they fill the taco with {food1}, cheese, and top it off with a salsa made from {food2}.")
    print(f"If that doesn't make your mouth water, then it's just like {person} always says: {saying}!")
elif answer == "No":
    print("Oh. Ok. I feel sad now. I put in all that effort. For nothing...")
    print("I'll read it to you anyways :)")
    print(f"Today I went to my favorite Taco Stand called the {adjective} {animal}. Unlike most food stands, they cook and prepare the food in a {ride} while you {verb}.")
    print(f" The best thing on the menu is the {color} {noun}. Instead of ground beef they fill the taco with {food1}, cheese, and top it off with a salsa made from {food2}. If that doesn't make your mouth water, then it's just like {person} always says: {saying}!")
else:
    print("HEY! YOU DIDN'T ANSWER THE QUESTION! I'M ANGRY NOW! I'M GONNA QUIT!!!")