name = input("Please enter name here: ")
print (f"Hello {name}")
input()
print (f"Here is your shape, {name}")
print ("     ______________________")
print ("    /                      \ ")
print ("   /                        \ ")
print ("  /                          \ ")
print (" /                            \ ")
print ("/                              \ ")
print ("\                              /")
print (" \                            /")
print ("  \                          /")
print ("   \                        /")
print ("    \                      /")
print ("      _____________________")